version: "3"
services:

  authserver:
    image: "golang:1.11"
    ports:
      - "5001:5001"
    command: "go run main.go"
    environment:
      - "AUTH_SERVER_MASTER_KEY=mypassword"
    working_dir: "/go/src/github.com/chartmuseum/auth-server-example/authserver"
    volumes:
      - "./authserver:/go/src/github.com/chartmuseum/auth-server-example/authserver:ro"
      - "./config:/go/src/github.com/chartmuseum/auth-server-example/config:ro"

  chartmuseum:
    image: "chartmuseum/chartmuseum:latest"
    ports:
      - "8080:8080"
    environment:
      - "DEBUG=1"
      - "DEPTH=2"
      - "ALLOW_OVERWRITE=1"
      - "STORAGE=local"
      - "STORAGE_LOCAL_ROOTDIR=/charts"
      - "BEARER_AUTH=1"
      - "AUTH_REALM=http://localhost:5001/oauth/token"
      - "AUTH_SERVICE=localhost:5001"
      - "AUTH_CERT_PATH=/config/server.pem"
    volumes:
      - "./config:/config:ro"