name: Docker Build and Push

on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/ci.yml'
    branches:
      - master
  release:
    types:
      - published

jobs:
  build-push:
    runs-on: ubuntu-latest
    name: Docker Build and Push
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Build,Tag latest and Push for Docker hub
        if: github.ref == 'refs/heads/master'
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: craftech/chartmuseum-auth-server
          dockerfile: Dockerfile
          tags: latest

      - name: Build, Tag Release and Push for Docker hub
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: craftech/chartmuseum-auth-server
          dockerfile: Dockerfile
          tags: ${GITHUB_REF##*/}

      - uses: craftech-io/slack-action@v1
        with:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_channel: deploy
        if: always()